#ifndef ARM_MOTION_CONFIG_H
#define ARM_MOTION_CONFIG_H

/* Generated by write_cfd_motion_config.m. Edit cfd_case_parameters.m instead. */
#define ARM_MOTION_PI 3.14159265358979323846

/* User-editable motion parameters. */
#define ARM_CFG_T_DEPLOY_S             2
#define ARM_CFG_T_WORK_S               6
#define ARM_CFG_T_RETRACT_S            2
#define ARM_CFG_Q1_STOW_DEG            0
#define ARM_CFG_Q2_STOW_DEG            0
#define ARM_CFG_Q3_STOW_DEG            0
#define ARM_CFG_Q1_WORK_DEG            -30
#define ARM_CFG_Q2_WORK_DEG            -50
#define ARM_CFG_Q3_WORK_DEG            -55
#define ARM_CFG_Q1_SWEEP_HALF_DEG      30
#define ARM_CFG_Q1_SWEEP_DIRECTION     1
#define ARM_CFG_TIME_STEP_S            0.01
#define ARM_CFG_PREVIEW_STEPS          30

/* Case metadata. */
#define ARM_CASE_DENSITY_KG_M3         1025
#define ARM_CASE_GRAVITY_M_S2          9.8100000000000005
#define ARM_CASE_CURRENT_SPEED_MPS     0.25
#define ARM_CASE_CURRENT_AZIMUTH_DEG   45
#define ARM_CASE_CURRENT_ELEVATION_DEG 0

/* Fixed validated geometry. */
#define ARM_FIXED_R12_X_M              0.016690119999999999
#define ARM_FIXED_R12_Y_M              0.050500000000000003
#define ARM_FIXED_R12_Z_M              -0.029999999999999999
#define ARM_FIXED_R23_X_M              -0.19800000000000001
#define ARM_FIXED_R23_Y_M              0.056000000000000001
#define ARM_FIXED_R23_Z_M              0.0018901199999999999
#define ARM_FIXED_JOINT1_CX_M          -0.74563400000000002
#define ARM_FIXED_JOINT1_CY_M          1.155872
#define ARM_FIXED_JOINT1_CZ_M          -1.1422399999999999
#define ARM_FIXED_JOINT2_CX_M          -0.72894400000000004
#define ARM_FIXED_JOINT2_CY_M          1.206372
#define ARM_FIXED_JOINT2_CZ_M          -1.1722399999999999
#define ARM_FIXED_JOINT3_CX_M          -0.73083399999999998
#define ARM_FIXED_JOINT3_CY_M          1.008372
#define ARM_FIXED_JOINT3_CZ_M          -1.22824

#define ARM_CFG_DEG_TO_RAD             (ARM_MOTION_PI / 180.0)
#define ARM_CFG_T_TOTAL_S              (ARM_CFG_T_DEPLOY_S + ARM_CFG_T_WORK_S + ARM_CFG_T_RETRACT_S)
#define ARM_CFG_OMEGA_B_RAD_S          (2.0 * ARM_MOTION_PI / ARM_CFG_T_WORK_S)
#define ARM_CFG_Q1_STOW_RAD            (ARM_CFG_Q1_STOW_DEG * ARM_CFG_DEG_TO_RAD)
#define ARM_CFG_Q2_STOW_RAD            (ARM_CFG_Q2_STOW_DEG * ARM_CFG_DEG_TO_RAD)
#define ARM_CFG_Q3_STOW_RAD            (ARM_CFG_Q3_STOW_DEG * ARM_CFG_DEG_TO_RAD)
#define ARM_CFG_Q1_WORK_RAD            (ARM_CFG_Q1_WORK_DEG * ARM_CFG_DEG_TO_RAD)
#define ARM_CFG_Q2_WORK_RAD            (ARM_CFG_Q2_WORK_DEG * ARM_CFG_DEG_TO_RAD)
#define ARM_CFG_Q3_WORK_RAD            (ARM_CFG_Q3_WORK_DEG * ARM_CFG_DEG_TO_RAD)
#define ARM_CFG_Q1_SWEEP_HALF_RAD      (ARM_CFG_Q1_SWEEP_HALF_DEG * ARM_CFG_DEG_TO_RAD)

#endif /* ARM_MOTION_CONFIG_H */
